# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mape_1', '0004_auto_20160809_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
