# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mape_1', '0005_auto_20160809_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_caption',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default='', upload_to=b'images/products/thumbnails'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=b'images/products/main'),
        ),
    ]
